# Generated by Django 4.2.23 on 2025-06-14 16:29

from django.db import migrations, models
import seguridadVial.models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='unica_area',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='elementos',
            name='id_categoria',
            field=models.ForeignKey(on_delete=models.SET(seguridadVial.models.seleccionar_categoria_remplazo), to='seguridadVial.categoria'),
        ),
        migrations.AlterField(
            model_name='elementos',
            name='id_persona',
            field=models.ForeignKey(on_delete=models.SET(seguridadVial.models.seleccionar_persona_remplazo), to='seguridadVial.persona'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='id_persona_encargado',
            field=models.ForeignKey(on_delete=models.SET(seguridadVial.models.seleccionar_persona_remplazo), related_name='encargado', to='seguridadVial.persona'),
        ),
        migrations.AlterField(
            model_name='institucionpersona',
            name='id_persona',
            field=models.ForeignKey(on_delete=models.SET(seguridadVial.models.seleccionar_persona_remplazo), to='seguridadVial.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cargo',
            field=models.ForeignKey(on_delete=models.SET(seguridadVial.models.seleccionar_cargo_remplazo), to='seguridadVial.cargo'),
        ),
    ]
