# Generated by Django 4.2.21 on 2025-05-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementos',
            name='cantidad',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
