# Generated by Django 4.2.23 on 2025-06-17 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catastrophe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_disaster', models.CharField(default=None, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('image_disaster', models.URLField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Refujio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('map_frame', models.TextField(blank=True, default=None, null=True)),
                ('catastrophe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refugios', to='seguridadVial.catastrophe')),
            ],
        ),
        migrations.CreateModel(
            name='Protocole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_seleccion', models.CharField(blank=True, choices=[('Antes', 'Antes'), ('Durante', 'Durante'), ('Despues', 'Despues')], default=None, max_length=50, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('catastrophe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocoles', to='seguridadVial.catastrophe')),
            ],
        ),
    ]
