# Generated by Django 4.2.23 on 2025-06-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='id_persona_encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguridadVial.persona'),
        ),
    ]
