# Generated by Django 4.2.23 on 2025-07-01 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('pk_catastrofe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridadVial.catastrophe')),
            ],
        ),
    ]
