# Generated by Django 4.2.23 on 2025-06-17 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0002_catastrophe_refujio_protocole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('catastrophe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_info', to='seguridadVial.catastrophe')),
            ],
        ),
    ]
