# Generated by Django 4.2.23 on 2025-07-01 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0002_pdfframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfframe',
            name='pk_catastrofe',
        ),
        migrations.CreateModel(
            name='CatPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridadVial.catastrophe')),
                ('id_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridadVial.pdfframe')),
            ],
        ),
        migrations.AddField(
            model_name='pdfframe',
            name='pk_catastrofe',
            field=models.ManyToManyField(through='seguridadVial.CatPdf', to='seguridadVial.catastrophe'),
        ),
    ]
