# Generated by Django 4.2.23 on 2025-06-14 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0002_alter_institucion_id_persona_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementos',
            name='id_persona',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='seguridadVial.persona'),
            preserve_default=False,
        ),
    ]
