# Generated by Django 4.2.23 on 2025-06-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0003_elementos_id_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='elementos',
            name='tipo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
