# Generated by Django 4.2.13 on 2025-04-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0003_alter_persona_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='telefono',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
