# Generated by Django 4.2.23 on 2025-07-11 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0003_remove_pdfframe_pk_catastrofe_catpdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCatastrofe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default=None, max_length=255)),
                ('id_catastrofe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridadVial.catastrophe')),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Antes', 'Antes'), ('Durante', 'Durante'), ('Despues', 'Despues')], default=None, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('subcatastrofe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocolos', to='seguridadVial.subcatastrofe')),
            ],
        ),
        migrations.CreateModel(
            name='Prevencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default=None, max_length=255)),
                ('descripcion', models.TextField(default=None)),
                ('subcatastrofe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prevenciones', to='seguridadVial.subcatastrofe')),
            ],
        ),
    ]
