# Generated by Django 4.2.23 on 2025-06-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0003_footer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer_info',
            name='icono',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
