# Generated by Django 4.2.23 on 2025-06-18 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0004_footer_info_icono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refujio',
            old_name='name',
            new_name='Refujio',
        ),
    ]
