# Generated by Django 4.2.23 on 2025-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0004_alter_elementos_observaciones_alter_elementos_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementos',
            name='estado',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
