# Generated by Django 4.2.23 on 2025-06-21 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0005_rename_name_refujio_refujio'),
    ]

    operations = [
        migrations.CreateModel(
            name='url_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default=None, max_length=700, null=True)),
                ('colors', models.CharField(blank=True, default=None, max_length=700, null=True)),
                ('catastrophe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='seguridadVial.catastrophe')),
            ],
        ),
    ]
