# Generated by Django 4.2.30 on 2026-06-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0005_integrantesdc'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='orden',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
