# Generated by Django 4.2.23 on 2025-06-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0006_url_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refujio',
            name='map_frame',
            field=models.CharField(blank=True, default=None, max_length=555, null=True),
        ),
    ]
