# Generated by Django 4.2.23 on 2025-06-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0007_alter_refujio_map_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='catastrophe',
            name='descripcion',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
