# Generated by Django 4.2.23 on 2025-06-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0008_catastrophe_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer_info',
            name='icono',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
