# Generated by Django 4.2.23 on 2025-06-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0009_alter_footer_info_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='descripcion',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
    ]
