# Generated by Django 4.2.23 on 2025-06-26 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0010_institucion_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refujio',
            name='Refujio',
        ),
        migrations.RemoveField(
            model_name='refujio',
            name='catastrophe',
        ),
        migrations.RemoveField(
            model_name='refujio',
            name='map_frame',
        ),
        migrations.AddField(
            model_name='refujio',
            name='catastrofe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seguridadVial.catastrophe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refujio',
            name='institucion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seguridadVial.institucion'),
            preserve_default=False,
        ),
    ]
