# Generated by Django 4.2.23 on 2025-06-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0011_remove_refujio_refujio_remove_refujio_catastrophe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catastrophe',
            name='mapa_interactivo',
            field=models.URLField(default=None),
        ),
        migrations.DeleteModel(
            name='url_map',
        ),
    ]
