# Generated by Django 4.2.23 on 2025-06-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0012_catastrophe_mapa_interactivo_delete_url_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catastrophe',
            name='image_disaster',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='catastrophe',
            name='mapa_interactivo',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
