# Generated by Django 4.2.23 on 2025-06-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0013_alter_catastrophe_image_disaster_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer_info',
        ),
    ]
