# Generated by Django 4.2.23 on 2025-06-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0014_delete_footer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catastrophe',
            name='mapa_interactivo',
            field=models.CharField(default=None, max_length=855),
        ),
    ]
