# Generated by Django 4.2.23 on 2025-06-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0015_alter_catastrophe_mapa_interactivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementos',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguridadVial.persona'),
        ),
    ]
