# Generated by Django 4.2.23 on 2025-06-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadVial', '0016_alter_elementos_id_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucioncargopersona',
            name='id_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seguridadVial.cargo'),
        ),
    ]
